modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

#logoFile="examplemod.png" #optional
credits="Thanks go to NUDLAUFLAUCH for all of the textures" #optional
authors= "${mod_authors}"

description='''

Curd mod makes curd and many different food types that you can craft from Curd(or not).
It also adds new ores, armors, tools and weapons.

'''

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true

    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"